# Generated by Django 6.0.3 on 2026-04-03 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medical_images/%Y/%m/', verbose_name='Image médicale')),
                ('modality', models.CharField(choices=[('CT', 'Scanner CT'), ('MR', 'IRM / MRI'), ('CR', 'Radiographie'), ('US', 'Échographie'), ('PT', 'PET Scan'), ('OTHER', 'Autre')], default='CT', max_length=10, verbose_name='Modalité')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name="Description de l'examen")),
                ('patient_id', models.CharField(blank=True, default='ANONYMIZED', max_length=50, verbose_name='ID Patient (Anonymisé)')),
                ('ai_model', models.CharField(default='AtlasRad General v1.0', max_length=100, verbose_name='Modèle IA utilisé')),
                ('result', models.CharField(blank=True, max_length=500, verbose_name='Résultat IA')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Score de confiance (%)')),
                ('finding', models.TextField(blank=True, verbose_name='Description des findings')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'analyse")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='Radiologue')),
            ],
            options={
                'verbose_name': 'Analyse IA',
                'verbose_name_plural': 'Analyses IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
